#!/usr/bin/env bash
# This script displays specific information about the file /etc/passwd.

input="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$input"
