#!/usr/bin/env bash
# This script displays "Hi" in the Nineth line using a while loop

count=0
while [ $count -ne 11 ]
do
    if [ $count -eq 9 ]; then
	echo "Hi"
    else
	echo "Best School"
    fi
    ((count++))
done
