#!/usr/bin/env bash
# This script displays "Hi" in the Nineth line using a while loop

I=0
while [ $I -lt 10 ]
do
	if [ $I = 3 ]
	then
		echo "bad luck"
	elif [ $I = 7 ]
	then
		echo "good luck"
	else
		echo "best School"
	fi
	I=$((I + 1))
done
