#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

HOUR=0
while [ $HOUR -le 12 ]
do
	echo "Hour: $HOUR"
	MINUTE=1
	while [ $MINUTE -le 59 ]
	do
		echo "$MINUTE"
		MINUTE=$((MINUTE + 1))
	done
	HOUR=$((HOUR + 1))
done
