#!/usr/bin/env bash
# This script displays the contents of the current directory in list format.
# Only the part of the name after the first dash is displayed. 

for file in $( ls ):
do
	echo "$file" | cut -d "-" -f 2- | rev | cut -d ":" -f 2- | rev
done
