#!/usr/bin/env bash
# This script displays information about a file 

FILE="./School"
if [ -e $FILE ]
then
	echo "School file exists"
	if [ -s $FILE ]
	then
		echo "School file is not empty"
		if [ -f $FILE ]
		then
			echo "School is a regular file"
		fi
	else
		echo "School file is empty"
		if [ -f $FILE ]
		then
			echo "School is a regular file"
		fi
	fi
else
	echo "School file does not exist"
fi
